add_newline = false

right_format = """
$aws\
$golang\
$java\
$gradle\
$kotlin\
$kubernetes\
$memory_usage\
$nodejs\
"""

[username]
disabled = false
show_always = true
style_user = "bold yellow"
style_root= "bold red"
format = "[â•­â”€kaizen]($style)@"

[hostname]
disabled = false
ssh_only = false
style = "fg:#FFA577 bold"
format =  "[ecra]($style) âš¡ï¸"
trim_at = "-"

[directory]
disabled = false
truncate_to_repo = true
truncation_length = 0
home_symbol = "~"
format = "[$path](fg:#FFA500 bold)[/](fg:#FFD700 bold) "

[character]
error_symbol = "[â•° ó°Š ](fg:#FFA500 bold)"
success_symbol = "[â•°  îœ§](fg:#FFD700 bold)" 

[kubernetes]
symbol = 'ó±ƒ¾'
style = 'fg:#FFD700 bold'
format = '[$symbol ($cluster in )$context \($namespace\)]($style) '
disabled = false

[kotlin]
kotlin_binary = 'kotlin'
symbol = 'î˜´ '
style = 'fg:#FFD700 bold'
format = '[$symbol($version )]($style)'

[gradle]
style = 'fg:#FFA500 bold'
format = '[$symbol($version )]($style)'
symbol = 'î™  '

[aws]
symbol = "îŒ½"

[docker_context]
disabled = true
symbol = "ïŒˆ "
format = '[$symbol$context]($style) '

[git_branch]
symbol = "î™œ "
style = 'bold #FFD700'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
conflicted = 'âœ˜ ${count}(fg:#FFA500)'
ahead = 'â‡¡${count}(fg:#FFA500)'
diverged = 'ğŸŒª â‡•â‡¡${ahead_count}â‡£${behind_count}(fg:#FFA500)'
behind = 'ğŸ¢ â‡£${count}(fg:#FFA500)'
up_to_date = 'ğŸš€ (fg:#FFD700)'
untracked = 'ğŸŒŸ (fg:#FFD700)'
modified = 'ó°·¬ (fg:#FFA500)'
staged = '[ğŸ“¦ ++${count}](fg:#FFA500)'
style = 'bold dimmed #FFA500'

[golang]
symbol = "î™ "
style = 'fg:#FFD700 bold'
format = '[${symbol}(${version} )]($style)'

[java]
symbol = "î‰– "
style = 'fg:#FFA500 bold'
format = '[${symbol}(${version} )]($style)'

#[memory_usage]
#disabled = false
#threshold = -1
#symbol = ' '
#style = 'bold dimmed purple'
#format = '$symbol [${ram} | ${ram_pct}]($style) '

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
disabled = true

[php]
symbol = "îœ½ "

[rust]
symbol = "î¨ "