add_newline = false

right_format = """
$aws\
$golang\
$java\
$gradle\
$kotlin\
$kubernetes\
$nodejs\
"""

[username]
disabled = false
show_always = true
style_user = "bold #9370DB"  # MediumPurple
style_root = "bold #FF69B4"  # HotPink
format = "[â•­â”€kaizen]($style)@"

[hostname]
disabled = false
ssh_only = false
style = "bold #FF69B4"  # HotPink
format = "[ecra]($style) "
trim_at = "-"

[directory]
disabled = false
truncate_to_repo = true
truncation_length = 0
home_symbol = "~"
format = "[$path](fg:#9370DB bold)[/](fg:#FF69B4 bold) "  # MediumPurple y HotPink

[character]
error_symbol = "[â•° ó°Š ](fg:#9370DB dimmed bold)"  # MediumPurple
success_symbol = "[â•° ó°¥¬](fg:#9370DB bold)"  # MediumPurple

[kubernetes]
symbol = 'ó±ƒ¾'
style = 'fg:#FF69B4 bold'  # HotPink
format = '[$symbol ($cluster in )$context \($namespace\)]($style) '
disabled = false

[kotlin]
kotlin_binary = 'kotlin'
symbol = 'î˜´ '
style = 'fg:#FF69B4 bold'  # HotPink
format = '[$symbol($version )]($style)'

[gradle]
style = 'fg:#9370DB bold'  # MediumPurple
format = '[$symbol($version )]($style)'
symbol = 'î™  '

[docker_context]
disabled = true
symbol = "ïŒˆ "
format = '[$symbol$context]($style) '

[git_branch]
symbol = "î™œ "
style = 'fg:#FF69B4 bold'  # HotPink
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
conflicted = ' ğŸ³ '
ahead = ' ğŸğŸ’¨ '
behind = ' ğŸ˜° '
diverged = ' ğŸ˜µ '
up_to_date = ' âœ“ '
untracked = ' ğŸ¤· ' 
stashed = ' ğŸ“¦ '
modified = ' ğŸ“ '
staged = ' [++\($count\)](green) '
renamed = ' ğŸ‘… '
deleted = ' ğŸ—‘ '


[golang]
symbol = "î˜§ "
style = 'fg:#FF69B4 dimmed bold'  # HotPink
format = '[${symbol}(${version} )]($style)'

[java]
symbol = "î‰– "
style = 'fg:#9370DB bold'  # MediumPurple
format = '[${symbol}(${version} )]($style)'


[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
disabled = true

[php]
symbol = "îœ½ "

[rust]
symbol = "î¨ "